# Generated by Django 2.0.6 on 2018-06-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reg_no', models.CharField(max_length=20)),
                ('mail_id', models.EmailField(max_length=100)),
                ('mobile_no', models.CharField(max_length=10)),
                ('college', models.CharField(max_length=30)),
                ('pay_mode', models.CharField(max_length=6)),
                ('location_sale', models.CharField(max_length=15)),
                ('sale_type', models.CharField(max_length=15)),
                ('pch_name', models.CharField(max_length=20)),
                ('unique_id', models.CharField(max_length=135)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
