# Generated by Django 2.0.6 on 2018-06-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='unique_id',
            field=models.CharField(max_length=128),
        ),
    ]
